import { useState, useEffect, useContext } from 'react';
import axios from 'axios';
import { AuthContext } from '../context/AuthContext';
import Header from '../components/Header';
import { Download, Filter, Search, Calendar, FileText, CheckCircle, Clock, AlertCircle } from 'lucide-react';
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

const Reports = () => {
  const { user } = useContext(AuthContext);
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  
  // Filters
  const [statusFilter, setStatusFilter] = useState(''); // Empty means 'All'
  const [semesterFilter, setSemesterFilter] = useState('');
  const [searchQuery, setSearchQuery] = useState('');

  const API_URL = import.meta.env.VITE_API_URL || 'https://fac-dss-be.onrender.com/api';

  useEffect(() => {
    fetchReports();
  }, [statusFilter, semesterFilter]);

  const fetchReports = async () => {
    setLoading(true);
    try {
      const res = await axios.get(`${API_URL}/admin/reports`, {
        params: { status: statusFilter, semester: semesterFilter },
        headers: { Authorization: `Bearer ${user.token}` }
      });
      setReports(res.data);
    } catch (err) {
      console.error("Error fetching reports:", err);
    } finally {
      setLoading(false);
    }
  };

  // Client-side search filter
  const filteredReports = reports.filter(r => {
    if (!searchQuery) return true;
    const searchLower = searchQuery.toLowerCase();
    return (
      (r.faculty?.name || '').toLowerCase().includes(searchLower) ||
      (r.subject?.subjectCode || '').toLowerCase().includes(searchLower) ||
      (r.remarks || '').toLowerCase().includes(searchLower)
    );
  });

  const handleExportPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Header
    doc.setFontSize(16);
    doc.setTextColor(128, 0, 0); // SSU Maroon
    doc.text("SORSOGON STATE UNIVERSITY", pageWidth / 2, 15, { align: "center" });
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text("Faculty Attendance & Absence Report (DSS)", pageWidth / 2, 22, { align: "center" });
    
    doc.setFontSize(10);
    doc.text(`Generated By: ${user?.name} (${user?.role.toUpperCase()})`, 14, 35);
    doc.text(`Date Generated: ${new Date().toLocaleDateString()}`, 14, 40);
    doc.text(`Filters Applied: ${statusFilter || 'All Statuses'} | ${semesterFilter || 'All Semesters'}`, 14, 45);

    // Table Data Mapping
    const tableColumn = ["Date/Time", "Subject", "Instructor", "Status", "Remarks", "Reviewed By"];
    const tableRows = filteredReports.map(r => [
      new Date(r.createdAt).toLocaleString('en-US', { dateStyle: 'short', timeStyle: 'short' }),
      `${r.subject?.subjectCode || 'N/A'}`,
      r.faculty?.name || "Unknown",
      r.status,
      r.remarks || "None",
      r.reviewedBy?.name || "Pending"
    ]);

    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 55,
      theme: 'grid',
      headStyles: { fillColor:, textColor:, fontStyle: 'bold' },
      styles: { fontSize: 8, cellPadding: 3 },
      alternateRowStyles: { fillColor: }
    });

    doc.save(`FAC-DSS_Report_${new Date().getTime()}.pdf`);
  };

  const getStatusIcon = (status) => {
    switch(status) {
      case 'Accepted': return <CheckCircle size={16} className="text-green-600" />;
      case 'Pending': return <Clock size={16} className="text-orange-500" />;
      case 'Unconfirmed': return <AlertCircle size={16} className="text-gray-400" />;
      default: return <FileText size={16} className="text-gray-500" />;
    }
  };

  const getStatusStyle = (status) => {
    switch(status) {
      case 'Accepted': return 'bg-green-100 text-green-800 border-green-200';
      case 'Pending': return 'bg-orange-100 text-orange-800 border-orange-200';
      case 'Unconfirmed': return 'bg-gray-100 text-gray-800 border-gray-200';
      default: return 'bg-gray-100 text-gray-800 border-gray-200';
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 pb-20">
      <Header title="Master Reports" />
      
      <main className="max-w-7xl mx-auto p-6">
        
        {/* Page Header & Controls */}
        <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-200 mb-6">
          <div className="flex flex-col lg:flex-row justify-between items-start lg:items-center gap-4 mb-6">
            <div>
              <h2 className="text-2xl font-bold text-gray-800">System Master Records</h2>
              <p className="text-sm text-gray-500">Comprehensive view of all attendance logs and absence reports.</p>
            </div>
            
            <button 
              onClick={handleExportPDF}
              className="bg-green-700 hover:bg-green-800 text-white px-5 py-2.5 rounded-xl font-bold flex items-center gap-2 transition shadow-sm"
            >
              <Download size={18} /> Export PDF
            </button>
          </div>

          {/* Filter Bar */}
          <div className="flex flex-wrap items-center gap-3 pt-4 border-t border-gray-100">
            
            {/* Search */}
            <div className="relative flex-grow max-w-xs">
              <Search size={18} className="absolute left-3 top-3 text-gray-400" />
              <input 
                type="text" 
                placeholder="Search faculty or subject..." 
                className="w-full pl-10 pr-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:outline-none focus:border-ssu-maroon transition"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>

            {/* Status Filter */}
            <div className="relative">
              <Filter size={16} className="absolute left-3 top-3 text-gray-400" />
              <select 
                className="pl-9 pr-8 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm font-bold text-gray-700 focus:outline-none cursor-pointer"
                value={statusFilter}
                onChange={(e) => setStatusFilter(e.target.value)}
              >
                <option value="">All Statuses</option>
                <option value="Accepted">Accepted (Validated)</option>
                <option value="Pending">Pending Review</option>
                <option value="Unconfirmed">Unconfirmed (1 Report)</option>
              </select>
            </div>

            {/* Semester Filter */}
            <div className="relative">
              <Calendar size={16} className="absolute left-3 top-3 text-gray-400" />
              <select 
                className="pl-9 pr-8 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm font-bold text-gray-700 focus:outline-none cursor-pointer"
                value={semesterFilter}
                onChange={(e) => setSemesterFilter(e.target.value)}
              >
                <option value="">All Semesters</option>
                <option value="1st Sem 2025-2026">1st Sem 2025-2026</option>
                <option value="2nd Sem 2025-2026">2nd Sem 2025-2026</option>
              </select>
            </div>

          </div>
        </div>

        {/* Data Table */}
        <div className="bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm whitespace-nowrap">
              <thead className="bg-gray-100/50 text-gray-500 font-bold uppercase text-[11px] tracking-wider border-b border-gray-200">
                <tr>
                  <th className="px-6 py-4">Timestamp</th>
                  <th className="px-6 py-4">Subject</th>
                  <th className="px-6 py-4">Instructor</th>
                  <th className="px-6 py-4">Status</th>
                  <th className="px-6 py-4">HR Remarks</th>
                  <th className="px-6 py-4">Reviewed By</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {loading ? (
                  <tr>
                    <td colSpan="6" className="px-6 py-12 text-center text-ssu-maroon font-bold animate-pulse">
                      Loading records...
                    </td>
                  </tr>
                ) : filteredReports.length === 0 ? (
                  <tr>
                    <td colSpan="6" className="px-6 py-12 text-center text-gray-400">
                      No reports found matching your criteria.
                    </td>
                  </tr>
                ) : (
                  filteredReports.map((r) => (
                    <tr key={r._id} className="hover:bg-gray-50 transition">
                      <td className="px-6 py-4">
                        <p className="font-bold text-gray-700">
                          {new Date(r.createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                        </p>
                        <p className="text-xs text-gray-500">
                          {new Date(r.createdAt).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}
                        </p>
                      </td>
                      <td className="px-6 py-4">
                        <p className="font-bold text-gray-800">{r.subject?.subjectCode || 'N/A'}</p>
                        <p className="text-xs text-gray-500 truncate max-w-[150px]">{r.subject?.subjectName}</p>
                      </td>
                      <td className="px-6 py-4 font-medium text-gray-700">
                        {r.faculty?.name || 'Unknown'}
                      </td>
                      <td className="px-6 py-4">
                        <div className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-bold border ${getStatusStyle(r.status)}`}>
                          {getStatusIcon(r.status)} {r.status}
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        <span className="text-gray-600 font-medium">{r.remarks || '—'}</span>
                      </td>
                      <td className="px-6 py-4">
                        <span className="text-xs text-gray-500 font-medium bg-gray-100 px-2 py-1 rounded">
                          {r.reviewedBy?.name || 'Pending'}
                        </span>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>

      </main>
    </div>
  );
};

export default Reports;