import { useState, useEffect, useContext } from 'react';
import axios from 'axios';
import { AuthContext } from '../context/AuthContext';
import Header from '../components/Header';
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable"; // <--- FIX 1: Import as default
import { Download, Filter } from 'lucide-react';

const Reports = () => {
  const { user } = useContext(AuthContext);
  const [reportType, setReportType] = useState('attendance'); 
  const [semester, setSemester] = useState('1st Sem 2025-2026');
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    fetchData();
  }, [reportType, semester]);

  const fetchData = async () => {
    setLoading(true);
    try {
      let endpoint = '';
      let params = { semester };

      if (reportType === 'attendance') {
        endpoint = 'https://fac-dss-be.onrender.com/api/admin/reports';
        params.status = 'Accepted'; 
      } else if (reportType === 'faculty') {
        endpoint = 'https://fac-dss-be.onrender.com/api/admin/users?role=faculty'; 
      } else if (reportType === 'students') {
        endpoint = 'https://fac-dss-be.onrender.com/api/admin/users?role=student';
      }

      const res = await axios.get(endpoint, { 
        params, 
        headers: { Authorization: `Bearer ${user.token}` } 
      });
      setData(res.data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    
    // Header Info
    doc.setFontSize(14);
    doc.text(`SSU ${reportType.toUpperCase()} REPORT`, 14, 20);
    doc.setFontSize(10);
    doc.text(`Semester: ${semester}`, 14, 26);
    doc.text(`Generated by: ${user.name}`, 14, 30);

    let columns = [];
    let rows = [];

    // Define Columns based on type
    if (reportType === 'attendance') {
      columns = ["Date", "Faculty", "Subject", "Reason"];
      rows = data.map(d => [
        new Date(d.createdAt).toLocaleDateString(),
        d.faculty?.name || 'N/A',
        d.subject?.subjectCode || 'N/A',
        d.remarks
      ]);
    } else if (reportType === 'faculty') {
      columns = ["Name", "Email", "ID Number", "Department"];
      rows = data.map(d => [d.name, d.email, d.idNumber, d.department || 'N/A']);
    } else if (reportType === 'students') {
      columns = ["Name", "ID Number", "Course", "Section"];
      rows = data.map(d => [d.name, d.idNumber, d.course, d.section]);
    }

    // FIX 2: Call autoTable as a function, passing 'doc' as the first argument
    autoTable(doc, {
      head: [columns],
      body: rows,
      startY: 35,
      theme: 'grid',
      headStyles: { fillColor: [128, 0, 0] }, // SSU Maroon color
    });

    doc.save(`SSU_${reportType}_${semester}.pdf`);
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <Header title="Analytics & Reports" />
      
      <main className="max-w-7xl mx-auto p-6">
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200 mb-6 flex flex-col md:flex-row justify-between gap-4">
          
          <div className="flex gap-4">
            <div className="space-y-1">
              <label className="text-xs font-bold text-gray-500 uppercase">Report Type</label>
              <select 
                className="block w-48 p-2 bg-gray-50 border rounded-lg text-sm font-bold"
                value={reportType}
                onChange={(e) => setReportType(e.target.value)}
              >
                <option value="attendance">Absence Reports</option>
                <option value="faculty">Faculty List</option>
                <option value="students">Student List</option>
              </select>
            </div>

            <div className="space-y-1">
              <label className="text-xs font-bold text-gray-500 uppercase">Semester</label>
              <select 
                className="block w-48 p-2 bg-gray-50 border rounded-lg text-sm font-bold"
                value={semester}
                onChange={(e) => setSemester(e.target.value)}
              >
                <option value="1st Sem 2025-2026">1st Sem 2025-2026</option>
                <option value="2nd Sem 2025-2026">2nd Sem 2025-2026</option>
              </select>
            </div>
          </div>

          <button 
            onClick={downloadPDF}
            className="flex items-center gap-2 bg-green-600 text-white px-6 py-2 rounded-lg font-bold hover:bg-green-700 transition"
          >
            <Download size={18} /> Export PDF
          </button>
        </div>

        {/* Data Table Preview */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
          <table className="w-full text-sm text-left">
            <thead className="bg-gray-100 text-gray-600 font-bold uppercase text-xs">
              <tr>
                <th className="p-4">#</th>
                {reportType === 'attendance' && <><th className="p-4">Faculty</th><th className="p-4">Subject</th><th className="p-4">Remarks</th></>}
                {reportType === 'faculty' && <><th className="p-4">Name</th><th className="p-4">Department</th><th className="p-4">ID Number</th></>}
                {reportType === 'students' && <><th className="p-4">Name</th><th className="p-4">Course/Sec</th><th className="p-4">Email</th></>}
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {loading ? <tr><td colSpan="5" className="p-8 text-center text-gray-400">Loading data...</td></tr> : 
               data.map((item, idx) => (
                <tr key={idx} className="hover:bg-gray-50">
                  <td className="p-4 text-gray-400">{idx + 1}</td>
                  
                  {reportType === 'attendance' && <>
                    <td className="p-4 font-bold">{item.faculty?.name}</td>
                    <td className="p-4">{item.subject?.subjectCode}</td>
                    <td className="p-4"><span className="bg-red-50 text-red-600 px-2 py-1 rounded text-xs font-bold">{item.remarks}</span></td>
                  </>}

                  {reportType === 'faculty' && <>
                    <td className="p-4 font-bold text-gray-800">{item.name}</td>
                    <td className="p-4">{item.department || 'N/A'}</td>
                    <td className="p-4 font-mono text-xs">{item.idNumber}</td>
                  </>}

                  {reportType === 'students' && <>
                    <td className="p-4 font-bold text-gray-800">{item.name}</td>
                    <td className="p-4"><span className="bg-blue-50 text-blue-600 px-2 py-1 rounded text-xs font-bold">{item.course} {item.section}</span></td>
                    <td className="p-4 text-gray-500">{item.email}</td>
                  </>}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </main>
    </div>
  );
};

export default Reports;